# Generated by Django 3.0.5 on 2020-04-24 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200422_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscribed',
            field=models.CharField(default='False', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 24, 17, 12, 33, 793444)),
        ),
        migrations.AlterField(
            model_name='groupinvitation',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 24, 17, 12, 33, 796436)),
        ),
        migrations.AlterField(
            model_name='grouprole',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 24, 17, 12, 33, 795439)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 24, 17, 12, 33, 792447)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 24, 17, 12, 33, 792447)),
        ),
        migrations.AlterField(
            model_name='plan',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 24, 17, 12, 33, 791447)),
        ),
    ]
