# Generated by Django 3.0.5 on 2020-04-22 12:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uploads', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('deadline', models.CharField(blank=True, max_length=20, null=True)),
                ('date_updated', models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 22, 17, 37, 5, 188820))),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AssignmentCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('file', models.ManyToManyField(blank=True, null=True, to='uploads.Files')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AssignmentGroup', to='users.Group')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineClassRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('time', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('date_updated', models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 22, 17, 37, 5, 198795))),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='OnlineClassRoomCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('description', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('date_updated', models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 22, 17, 37, 5, 183833))),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='NotesOwnerCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('file', models.ManyToManyField(blank=True, null=True, to='uploads.Files')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NotesOwner', to='users.Group')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 22, 17, 37, 5, 190815))),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Assignment')),
                ('file', models.ManyToManyField(blank=True, null=True, to='uploads.Files')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
