# Generated by Django 3.0.5 on 2020-04-22 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 22, 17, 57, 15, 785649)),
        ),
        migrations.AlterField(
            model_name='assignmentsubmit',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 22, 17, 57, 15, 786647)),
        ),
        migrations.AlterField(
            model_name='notes',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 22, 17, 57, 15, 783652)),
        ),
        migrations.AlterField(
            model_name='onlineclassroom',
            name='date_updated',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 22, 17, 57, 15, 788641)),
        ),
    ]
